#!/usr/bin/bash
echo 'Files will be moved to <their name>.bkup'
echo 'Requires arch linux.'
echo 'It assumes you DO NOT have my dotfiles installed,'
echo 'but rather that it has been git cloned into ~/dotfiles'
echo 'It assures you have a graphics card'
echo 'Please make sure these requirements are fulfilled'
echo
read -p "Do you want to continue? " -n 1 -r
[[ "$REPLY" =~ ^[Yy]$ ]] || exit 1

cd "$HOME"

#Yaourt
bash installs/yaourt.sh

#Basic installs
echo "Installing basic things"
bash installs/basic-installs.sh

#dotfiles setup
bash installs/dotfiles-setup.sh

# vim setup
bash installs/vim.sh

# MPD - music player daemon
bash installs/mpd.sh
