#!/bin/bash
echo 'Files will be moved to "their name".bkup'
echo 'Requires arch linux. INSTALLS YAOURT-GIT'
echo "It will now ask for your password (as a sudo authenticator)"
echo "It assumes you DO NOT have \`linuxfiles\` installed."
echo "It assumes you have a graphics driver installed"
echo "Please make sure these requirements are fulfilled"
echo
read -p "Do you want to continue? " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit 1; fi

cd $HOME

#Yaourt
if [ ! -f /usr/bin/yaourt ]; then
	echo "Installing yaourt"
	mkdir abs && cd abs
	curl -L "https://aur.archlinux.org/packages/ya/yaourt-git/yaourt-git.tar.gz" > yaourt-git.tar.gz
	curl -L "https://aur.archlinux.org/packages/pa/package-query-git/package-query-git.tar.gz" > package-query-git.tar.gz
	tar xf package-query-git.tar.gz && cd package-query-git
	makepkg -sci
	cd .. && tar xf yaourt-git.tar.gz && cd yaourt-git
	makepkg -sci
fi

#Basic installs
echo "Installing basic things"
	yaourt -Syu
	yaourt -S zsh xorg-server xorg-server-utils xorg-apps xorg-xinit ctags
	yaourt -S awesome gvmtool screenfetch xfluxd-args pgem-git rakudo
	yaourt -S jdk otf-meslo-powerline-git ttf-meslo gvim scrot alsa-utils
	read -p "Edit xfluxd-args settings? " -n 1 -r
	if [[ $REPLY =~ ^[Yy]$ ]]; then nano /etc/xfluxd-args.conf; fi
	systemctl --user enable xfluxd-args
	#read -p "Running xserver test. Type \`pkill x\` to exit. [Any key to continue] " -n 1 -r
	#echo
	#startx
	git clone git://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh
	echo "Setting zsh as default shell"
	chsh -s $(which zsh)

#linuxfiles setup
git clone https://github.com/czipperz/linuxfiles
git clone https://github.com/czipperz/b
git clone https://github.com/czipperz/gd
	if [ -f .gitconfig ]; then mv .gitconfig .gitconfig.bkup; fi
	ln linuxfiles/gitconfig $HOME/.gitconfig

	#Setup awesome
	if [ ! -d .config/awesome ]; then mkdir -p .config/awesome/themes; fi
	if [ ! -d .config/awesome/themes/transBlack ]; then
		git clone https://github.com/czipperz/awesomeThemes
		cp -R awesomeThemes/trans* .config/awesome/themes
	fi
	ln linuxfiles/rc.lua .config/awesome
	ln linuxfiles/czipperz.zsh-theme .oh-my-zsh/themes
	if [ -f .xinitrc ]; then mv .xinitrc .xinitrc.bkup; fi
	ln linuxfiles/xinitrc .xinitrc
	curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh

	echo "Installing b"
	sudo cp b /usr/bin
	mkdir .oh-my-zsh/functions
	ln b/_b .oh-my-zsh/functions

	echo "Installing gd"
	sudo cp gd/gd /usr/bin

# vim setup
if [ -f .vimrc ]; then mv .vimrc .vimrc.bkup; fi
	echo "source $HOME/linuxfiles/vim/vimrc.vim" > .vimrc
	mkdir -p $HOME/.vim/{tmp/undo,backup}
	curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
	git clone https://github.com/ChrisKempson/Tomorrow-Theme $HOME/.vim/bundle/Tomorrow-Theme
	cp -R $HOME/.vim/bundle/Tomorrow-Theme/vim/colors $HOME/.vim

read -p "Do you want my work files? " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit 0; fi

git clone https://github.com/czipperz/hbml
git clone https://github.com/czipperz/czipperz.github.io
git clone https://github.com/czipperz/chsWebsiteDraft

yaourt -S intellij-idea-ce-eap
