#!/bin/bash
# MPD - music player daemon
yaourt -S mpd ncmpcpp-git
	mkdir -p $HOME/.config/mpd/playlists
	touch $HOME/.config/mpd/{database,log,pid,state,sticker.sql}
	ln $HOME/dotfiles/mpd.conf $HOME/.config/mpd/mpd.conf
